# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
